#!/usr/bin/env python3
"""Generate the two larger site configurations.

``house_museum.yaml`` is written by hand because it is small enough to read. The palazzo
(25 rooms, two floors) and the national museum (60 rooms, several wings, multiple
entrances) are generated here so that their topology is provably consistent -- every wing
closes into a loop, every room is reachable from outside and can reach it again -- rather
than hand-typed and subtly broken.

The generated files are committed. Re-run this script only when the layout itself
changes, and commit the result.

Usage::

    python scripts/build_site_configs.py
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from mflow.graph import BuildingGraph
from mflow.paths import configs_dir
from mflow.sim.config import SiteConfig

HEADER = (
    "# Generated by scripts/build_site_configs.py. Edit the generator, not this file.\n"
)


def _node(
    node_id: str,
    name: str,
    kind: str,
    area: float,
    capacity: int,
    interest: float,
    height: float = 4.5,
) -> dict[str, Any]:
    return {
        "id": node_id,
        "name": name,
        "kind": kind,
        "area_m2": area,
        "capacity_persons": capacity,
        "interest": interest,
        "ceiling_height_m": height,
    }


def _edge(
    edge_id: str,
    src: str,
    dst: str,
    width: float,
    capacity: float,
    seconds: float = 12.0,
) -> dict[str, Any]:
    return {
        "id": edge_id,
        "src": src,
        "dst": dst,
        "width_m": width,
        "capacity_persons_per_min": capacity,
        "traversal_seconds": seconds,
    }


def palazzo() -> dict[str, Any]:
    """A 25-room palazzo: two floors, two loops per floor, one bottleneck corridor.

    The ground floor is a courtyard-style ring of state rooms; the first floor is the
    picture gallery. The two are joined by a monumental staircase and a single service
    corridor whose capacity is a third of everything around it, which is what makes the
    congestion experiment non-trivial.
    """
    nodes = [_node("outside", "Outside", "outside", 0, 0, 0.0)]
    edges = []

    nodes.append(_node("atrio", "Atrio", "entrance", 120, 80, 0.4, 7.0))
    nodes.append(_node("cortile", "Cortile", "gallery", 220, 130, 0.8, 12.0))
    nodes.append(_node("biglietteria", "Ticket hall", "corridor", 70, 45, 0.1, 5.0))
    edges.append(_edge("e_portal", "outside", "atrio", 3.0, 90, 10))
    edges.append(_edge("e_atrio_big", "atrio", "biglietteria", 2.4, 70, 10))
    edges.append(_edge("e_big_cort", "biglietteria", "cortile", 2.6, 75, 14))

    # Ground floor: eight state rooms in a ring off the courtyard.
    ground = [
        ("sala_trono", "Throne room", 150, 70, 2.2),
        ("sala_arazzi", "Tapestry room", 110, 55, 1.6),
        ("sala_musica", "Music room", 95, 45, 1.3),
        ("biblioteca", "Library", 130, 60, 1.9),
        ("sala_verde", "Green room", 85, 40, 1.0),
        ("sala_rossa", "Red room", 88, 42, 1.1),
        ("cappella", "Chapel", 105, 50, 2.0),
        ("sala_armi", "Armoury", 100, 48, 1.7),
    ]
    for node_id, name, area, capacity, interest in ground:
        nodes.append(_node(node_id, name, "gallery", area, capacity, interest, 8.0))
    ring = [row[0] for row in ground]
    for i, node_id in enumerate(ring):
        nxt = ring[(i + 1) % len(ring)]
        edges.append(_edge(f"e_gf_{i}", node_id, nxt, 1.8, 36, 14))
    edges.append(_edge("e_cort_gf", "cortile", ring[0], 2.2, 60, 12))
    edges.append(_edge("e_gf_cort", ring[4], "cortile", 2.0, 55, 12))

    # The bottleneck: a narrow service corridor linking the ring to the stair lobby.
    nodes.append(_node("corridoio", "Service corridor", "corridor", 40, 22, 0.1, 3.2))
    nodes.append(_node("scalone", "Grand staircase", "stair", 90, 40, 0.9, 14.0))
    edges.append(_edge("e_gf_corr", ring[2], "corridoio", 1.0, 12, 18))
    edges.append(_edge("e_corr_scal", "corridoio", "scalone", 1.1, 14, 20))
    edges.append(_edge("e_cort_scal", "cortile", "scalone", 2.4, 55, 16))

    # First floor: the picture gallery, two loops sharing a landing.
    nodes.append(_node("loggia", "Loggia", "corridor", 95, 55, 0.5, 6.0))
    edges.append(_edge("e_scal_log", "scalone", "loggia", 2.0, 45, 22))

    first = [
        ("pinacoteca_1", "Pinacoteca I", 140, 65, 2.4),
        ("pinacoteca_2", "Pinacoteca II", 135, 62, 2.3),
        ("pinacoteca_3", "Pinacoteca III", 120, 58, 1.8),
        ("gabinetto", "Cabinet of drawings", 55, 25, 2.6),
        ("sala_ceramiche", "Ceramics room", 90, 44, 1.2),
        ("sala_bronzi", "Bronzes", 85, 40, 1.4),
        ("terrazza", "Terrace room", 100, 48, 1.0),
        ("sala_moderna", "Modern room", 115, 55, 1.5),
    ]
    for node_id, name, area, capacity, interest in first:
        nodes.append(_node(node_id, name, "gallery", area, capacity, interest, 6.5))
    loop_a = ["loggia", "pinacoteca_1", "pinacoteca_2", "pinacoteca_3", "gabinetto"]
    loop_b = ["loggia", "sala_ceramiche", "sala_bronzi", "terrazza", "sala_moderna"]
    for label, loop in (("a", loop_a), ("b", loop_b)):
        for i in range(len(loop)):
            edges.append(
                _edge(f"e_ff_{label}{i}", loop[i], loop[(i + 1) % len(loop)], 1.6, 32, 14)
            )

    nodes.append(_node("bookshop", "Bookshop", "gallery", 80, 45, 0.6, 4.0))
    nodes.append(_node("uscita", "Exit hall", "exit", 60, 40, 0.1, 5.0))
    edges.append(_edge("e_cort_shop", "cortile", "bookshop", 1.8, 40, 12))
    edges.append(_edge("e_shop_usc", "bookshop", "uscita", 2.0, 50, 10))
    edges.append(_edge("e_usc_out", "uscita", "outside", 3.0, 90, 10))

    return {
        "site_id": "sim_palazzo",
        "timezone": "Europe/Rome",
        "interval_seconds": 60,
        "step_seconds": 10,
        "nodes": nodes,
        "edges": edges,
        "suggested_route": [
            "atrio", "biglietteria", "cortile", *ring, "scalone", "loggia",
            *loop_a[1:], *loop_b[1:], "bookshop", "uscita",
        ],
        "arrivals": {
            "open_time": "09:00",
            "close_time": "19:00",
            "peak_rate_per_min": 6.5,
            "hourly_profile": [0.30, 0.62, 0.85, 1.00, 0.78, 0.60, 0.82, 0.95, 0.55, 0.22],
            "weekday_multiplier": [0.0, 0.85, 0.9, 0.95, 1.15, 1.7, 1.6],
            "entrances": {"atrio": 1.0},
        },
        "style_mix": {"ant": 0.25, "fish": 0.25, "butterfly": 0.33, "grasshopper": 0.17},
        "groups": [
            {"id": "school_a", "time": "09:30", "size_mean": 28, "size_sd": 5,
             "cohesion": 0.9, "guided": True, "weekdays": [1, 2, 3, 4], "entrance": "atrio"},
            {"id": "school_b", "time": "11:00", "size_mean": 26, "size_sd": 5,
             "cohesion": 0.9, "guided": True, "weekdays": [1, 2, 3], "entrance": "atrio"},
            {"id": "tour_noon", "time": "12:00", "size_mean": 18, "size_sd": 4,
             "cohesion": 0.8, "guided": True, "entrance": "atrio"},
            {"id": "coach_pm", "time": "14:30", "size_mean": 45, "size_sd": 8,
             "cohesion": 0.55, "guided": False, "entrance": "atrio"},
            {"id": "tour_late", "time": "16:30", "size_mean": 20, "size_sd": 4,
             "cohesion": 0.8, "guided": True, "weekdays": [4, 5, 6], "entrance": "atrio"},
        ],
        "base_dwell_minutes": 1.8,
        "fatigue_per_minute": 0.006,
        "targets": {
            "mean_visit_minutes": [35.0, 120.0],
            "node_visit_fraction": [0.25, 0.90],
            "occupancy_peak_to_mean": [1.4, 5.0],
        },
    }


def national() -> dict[str, Any]:
    """A 60-room national museum: four wings off a central hall, three entrances."""
    nodes = [_node("outside", "Outside", "outside", 0, 0, 0.0)]
    edges = []

    nodes.append(_node("great_hall", "Great hall", "entrance", 600, 400, 0.6, 16.0))
    nodes.append(_node("north_door", "North entrance", "entrance", 140, 90, 0.2, 8.0))
    nodes.append(_node("west_door", "West entrance", "entrance", 120, 80, 0.2, 8.0))
    nodes.append(_node("rotunda", "Rotunda", "gallery", 380, 220, 1.4, 18.0))
    nodes.append(_node("main_stair", "Main staircase", "stair", 160, 80, 0.5, 14.0))
    nodes.append(_node("east_stair", "East staircase", "stair", 90, 45, 0.3, 14.0))
    nodes.append(_node("shop", "Museum shop", "gallery", 200, 110, 0.7, 6.0))
    nodes.append(_node("cafe", "Cafe", "gallery", 240, 140, 0.5, 6.0))
    nodes.append(_node("exit_hall", "Exit hall", "exit", 180, 120, 0.1, 8.0))

    edges += [
        _edge("e_main_in", "outside", "great_hall", 6.0, 200, 12),
        _edge("e_north_in", "outside", "north_door", 3.0, 90, 12),
        _edge("e_west_in", "outside", "west_door", 3.0, 80, 12),
        _edge("e_north_hall", "north_door", "great_hall", 3.2, 85, 18),
        _edge("e_west_hall", "west_door", "rotunda", 3.0, 80, 18),
        _edge("e_hall_rot", "great_hall", "rotunda", 4.5, 140, 16),
        _edge("e_rot_stair", "rotunda", "main_stair", 2.8, 70, 20),
        _edge("e_hall_cafe", "great_hall", "cafe", 2.6, 65, 14),
        _edge("e_hall_shop", "great_hall", "shop", 2.6, 65, 14),
        _edge("e_shop_exit", "shop", "exit_hall", 3.0, 90, 12),
        _edge("e_hall_exit", "great_hall", "exit_hall", 4.0, 120, 12),
        _edge("e_exit_out", "exit_hall", "outside", 6.0, 200, 10),
    ]

    wings = [
        ("ant", "Antiquities", "rotunda", 1.9, 12),
        ("med", "Medieval", "main_stair", 1.6, 12),
        ("mod", "Modern", "main_stair", 1.5, 13),
        ("eth", "Ethnography", "great_hall", 1.3, 14),
    ]
    route: list[str] = ["great_hall", "rotunda"]
    for prefix, label, anchor, interest, count in wings:
        wing_nodes = []
        for i in range(count):
            node_id = f"{prefix}_{i:02d}"
            nodes.append(
                _node(
                    node_id,
                    f"{label} {i + 1}",
                    "gallery",
                    110 + 12 * (i % 5),
                    50 + 6 * (i % 5),
                    round(interest * (0.7 + 0.1 * (i % 4)), 2),
                    7.0,
                )
            )
            wing_nodes.append(node_id)
        # A spine corridor down the wing, with the rooms hung off it in a loop so that
        # visitors can circulate back rather than reversing down a dead end.
        corridor = f"{prefix}_corridor"
        nodes.append(
            _node(corridor, f"{label} corridor", "corridor", 150, 70, 0.2, 5.0)
        )
        edges.append(_edge(f"e_{prefix}_anchor", anchor, corridor, 2.4, 55, 16))
        for i, node_id in enumerate(wing_nodes):
            edges.append(_edge(f"e_{prefix}_c{i}", corridor, node_id, 1.5, 30, 12))
            if i + 1 < len(wing_nodes):
                edges.append(
                    _edge(f"e_{prefix}_l{i}", node_id, wing_nodes[i + 1], 1.4, 26, 12)
                )
        route.extend([corridor, *wing_nodes])
    route.extend(["shop", "exit_hall"])
    edges.append(_edge("e_east_link", "eth_corridor", "east_stair", 1.8, 35, 20))
    edges.append(_edge("e_east_mod", "east_stair", "mod_corridor", 1.8, 35, 20))

    return {
        "site_id": "sim_national",
        "timezone": "Europe/Rome",
        "interval_seconds": 60,
        "step_seconds": 10,
        "nodes": nodes,
        "edges": edges,
        "suggested_route": route,
        "arrivals": {
            "open_time": "09:00",
            "close_time": "20:00",
            "peak_rate_per_min": 22.0,
            "hourly_profile": [
                0.35, 0.70, 0.92, 1.00, 0.85, 0.72, 0.88, 0.96, 0.74, 0.42, 0.18
            ],
            "weekday_multiplier": [0.0, 0.9, 0.95, 1.0, 1.2, 1.8, 1.7],
            "entrances": {"great_hall": 0.6, "north_door": 0.25, "west_door": 0.15},
        },
        "style_mix": {"ant": 0.20, "fish": 0.30, "butterfly": 0.32, "grasshopper": 0.18},
        "groups": [
            {"id": "school_1", "time": "09:30", "size_mean": 30, "size_sd": 6,
             "cohesion": 0.9, "guided": True, "weekdays": [1, 2, 3, 4],
             "entrance": "north_door"},
            {"id": "school_2", "time": "10:15", "size_mean": 28, "size_sd": 6,
             "cohesion": 0.9, "guided": True, "weekdays": [1, 2, 3, 4],
             "entrance": "north_door"},
            {"id": "tour_1", "time": "11:00", "size_mean": 22, "size_sd": 4,
             "cohesion": 0.8, "guided": True, "entrance": "great_hall"},
            {"id": "coach_1", "time": "11:30", "size_mean": 50, "size_sd": 9,
             "cohesion": 0.5, "guided": False, "entrance": "great_hall"},
            {"id": "coach_2", "time": "14:00", "size_mean": 55, "size_sd": 10,
             "cohesion": 0.5, "guided": False, "entrance": "west_door"},
            {"id": "tour_2", "time": "15:30", "size_mean": 24, "size_sd": 5,
             "cohesion": 0.8, "guided": True, "entrance": "great_hall"},
            {"id": "tour_evening", "time": "18:00", "size_mean": 16, "size_sd": 4,
             "cohesion": 0.8, "guided": True, "weekdays": [4, 5],
             "entrance": "great_hall"},
        ],
        "base_dwell_minutes": 1.4,
        "fatigue_per_minute": 0.005,
        "targets": {
            "mean_visit_minutes": [40.0, 160.0],
            "node_visit_fraction": [0.10, 0.70],
            "occupancy_peak_to_mean": [1.3, 5.0],
        },
    }


def write(payload: dict[str, Any], path: Path) -> None:
    """Validate the configuration, check the topology, and write it."""
    config = SiteConfig.model_validate(payload)
    nodes, edges = _frames(config)
    BuildingGraph.from_frames(nodes, edges).check_connectivity()
    path.write_text(
        HEADER + yaml.safe_dump(payload, sort_keys=False, width=100), encoding="utf-8"
    )
    print(f"wrote {path} ({len(config.nodes)} nodes, {len(config.edges)} doorways)")


def _frames(config: SiteConfig) -> tuple[Any, Any]:
    import pandas as pd

    nodes = pd.DataFrame(
        [
            {
                "node_id": node.id,
                "name": node.name,
                "kind": node.kind,
                "area_m2": node.area_m2,
                "capacity_persons": node.capacity_persons,
            }
            for node in config.nodes
        ]
    )
    rows = []
    for edge in config.edges:
        rows.append(
            {
                "edge_id": f"{edge.id}_fwd",
                "src_node": edge.src,
                "dst_node": edge.dst,
                "width_m": edge.width_m,
                "capacity_persons_per_min": edge.capacity_persons_per_min,
                "reverse_edge_id": f"{edge.id}_rev" if edge.bidirectional else "",
            }
        )
        if edge.bidirectional:
            rows.append(
                {
                    "edge_id": f"{edge.id}_rev",
                    "src_node": edge.dst,
                    "dst_node": edge.src,
                    "width_m": edge.width_m,
                    "capacity_persons_per_min": edge.capacity_persons_per_min,
                    "reverse_edge_id": f"{edge.id}_fwd",
                }
            )
    return nodes, pd.DataFrame(rows)


def main() -> None:
    """Write both generated site configurations."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=configs_dir("sites"))
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    write(palazzo(), args.out / "palazzo.yaml")
    write(national(), args.out / "national.yaml")


if __name__ == "__main__":
    main()
